### ISSUE TITLE
Generated XML is non-deterministic due to sharedstrings

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rbx-dom#103]
Currently, any XML generated with rbx-dom is non-deterministic due to `sharedstrings` being changed every time, even if no asset/code files have been changed. This makes things like checksum verification impossible.

Reproduction steps:
1) Build a rojo project into `a.rbxlx`
2) Rebuild the rojo project again, this time into `b.rbxlx`
3) Run a diff to compare the files. Notice how the sharedstrings have changed even though no source/asset files were changed.

![image](https://user-images.githubusercontent.com/26460940/81593341-4aa1a200-938d-11ea-907f-50522afddcf6.png)

**Comment by triankl3** [comment]
This is definitely still an issue and I ran into it myself when trying to make an export script for remodel. 
I'm not able to export all assets and simply commit ones with changes, because `sharedstrings` end up changing their order randomly.

This removes the viability of using remodel to easily export all assets through one command and diff them, instead artists would have to go through with manually exporting their assets into a directory, remembering which assets were changed and which not, etc...

Way easier to have everything export into the filesystem and then commit what you see is different.

**Comment by LPGhatguy** [comment]
The binary format doesn't have this issue, and diffs within the XML are usually not readable. I recommend using the binary format if you can.

Should be an easy fix, just needs to happen. We should change the `HashMap` we use for the shared string dictionary to a `BTreeMap`.
