### ISSUE TITLE
Implement writing special CFrame cases in the binary format

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rbx-dom#129]
In the binary format, there are several special CFrame cases where the rotation matrix isn't written (see: [the documentation on CFrame](https://github.com/rojo-rbx/rbx-dom/blob/master/format/binary.md#cframe)).

PR #128 implements CFrame in the binary format for the most part, but doesn't write the special cases any differently than normal CFrames. This doesn't impact the functionality of rbx_binary any, but it does impact the space taken up by CFrames, so writing these special cases should be implemented at some point.

**Comment by kennethloeffler** [comment]
I've implemented this on 5ae9d211b967bbb423c57a55747f3a5cc61581ac but with this approach the code is pretty crazy. This is mainly due to https://github.com/rust-lang/rust/issues/41620 (tl;dr float comps in patterns will cause a compiler error in the near future); using a match for this thus requires guards. Clippy doesn't much like these either so the specific lint has been silenced here. Thoughts, suggestions, alternative approaches?

**Comment by Dekkonot** [comment]
The way it's done in [**Roblox-File-Format**](https://github.com/CloneTrooper1019/Roblox-File-Format) might be worth investigating, though that will run into a similiar problem with regards to matching floats. We can probably get around that with casting though.

Related code: https://github.com/CloneTrooper1019/Roblox-File-Format/blob/master/DataTypes/CFrame.cs#L466-482
