### ISSUE TITLE
Clippy doesn't actually do anything right now

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rbx-dom#137]
Clippy runs on every commit on master or in a PR but it isn't configured, so even basic things like `unused-variables` doesn't raise an error. This is problematic, since it means that our attempts at linting aren't actually working. As an example, go look at the results from running clippy in the latest commit at the time of writing (linked [here](https://github.com/rojo-rbx/rbx-dom/runs/1366756378) for convenience). It has many lints, but none of them caused the CI to fail.

We should probably make it actually raise errors so that the CI does something.

**Comment by LPGhatguy** [comment]
fwiw, this was a conscious choice I made at the time. Running clippy on every commit is good to surface issues, but I decided against making all lints into errors. Clippy does stabilize new lints from time to time, but failing CI on them isn't quite fair.

There was a brief discussion in Discord about some of the approaches we could take to opt into many Clippy lints, but because this repository is a large workspace, all of them are a little tricky.
