### ISSUE TITLE
(rbx-binary) Rojo6 Unknown binary chunk name SSTR

### ISSUE THREAD

**Issue by MaxBorsch** [rojo-rbx/rbx-dom#185]
`rojo5 serve` works but `rojo6 serve` crashes with this error:

![Code_axr5Hf6C1M](https://user-images.githubusercontent.com/2924585/120913352-54a6da80-c64b-11eb-8dd8-b71172ad76f6.png)

**Comment by LPGhatguy** [comment]
The error message here is not actually about the unknown chunk name, it's the `InvalidTypeError` note a little lower.

In any case, we've fixed this in rbx-dom and Rojo 7. It required a number of breaking changes, which is why we can't make Rojo 6's binary support better without a lot of work.

I recommend sticking to XML (rbxlx and rbxmx) for Rojo 6, and upgrading to binary when Rojo 7 reaches stable.
