### ISSUE TITLE
`rbx_dom_weak` should provide a way to clone instances

### ISSUE THREAD

**Issue by kennethloeffler** [rojo-rbx/rbx-dom#282]
It's a pain for consumers to implement instance cloning themselves. I think `rbx_dom_weak` should give them a way to do it, and it should have the same semantics as Roblox's `Instance:Clone`:

* All of the instance's descendants are also cloned (i.e. the entire subtree is cloned),
* Any `Ref` properties in the cloned subtree that point to instances also contained in the subtree (i.e. point to instances that were cloned) are rewritten to point to the cloned instances,
* The instance at the root of the sub-tree is returned and its parent is set to the none `Ref`.

I'm a little torn about whether this should be an `impl Clone for Instance` or a method on `WeakDom` - I'd appreciate some input here.

**Comment by filiptibell** [comment]
I would love to see this as a native addition to `rbx-dom`. Doing this work as a consumer was tricky to get right without first understanding dom internals, and it will probably get even trickier if we decide to support things such as attributes with an `Instance` type, which has been hinted at by Roblox staff multiple times.

> I'm a little torn about whether this should be an `impl Clone for Instance` or a method on `WeakDom`

I think the ref behavior for the new subtree might be a little surprising if we were to call it a standard clone impl, mostly because it would leave refs pointing to instances outside of the subtree intact. It's not as "pure" of a clone as cloning a string, vec, etc would be. I also think using `Ref` here could be more ergonomic in cases that may involve multithreading or juggling lifetimes, because it is `Copy`.

**Comment by kennethloeffler** [comment]
Some thoughts on the API...

Based on usage in Lune, we might have a pair of functions, `WeakDom::clone_within` and `WeakDom::clone_into`:
```rust
    // Clone an instance into the same WeakDom
    pub fn clone_within(&mut self, referent: Ref) -> Ref

    // Clone an instance into an external WeakDom
    pub fn clone_into(&self, referent: Ref, dest: &mut WeakDom) -> Ref
```
These methods return the root ref of the cloned subtree, and always orphan the root of the cloned subtree (so no `parent` param is necessary), as per
```
The instance at the root of the sub-tree is returned and its parent is set to the none Ref.
```

**Comment by Dekkonot** [comment]
I like that API. `Instance` doesn't really exist outside of WeakDom and it conceptually makes sense to have us handle cloning them so that any logic can be done consistently. Stuff like rewriting `Ref` properties is tedious to do correctly and it makes sense for us to handle it.
