### ISSUE TITLE
rbx_reflector is inconsistent with storing default values for properties

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rbx-dom#345]
As discovered in #344, defaults for properties seem to not be always filled in on the first run of rbx_reflector. This seems to be resolved by running it multiple times, but it's spooky behavior so we should fix or mitigate it.

**Comment by kennethloeffler** [comment]
This is happening because rbx_reflector is using `DecodePropertyBehavior::IgnoreUnknown` when deserializing the defaults place, so it will only apply defaults for properties that are already present in the reflection database:
https://github.com/rojo-rbx/rbx-dom/blob/87d61fcf5c5ce583b3755c9938ffb662981ddcd1/rbx_reflector/src/defaults.rs#L14-L21

This is not the desired behavior. We should be using `DecodePropertyBehavior::NoReflection` and then using the in-progress database (rather than the one in rbx_xml) to do reflection on the defaults place, similar to generate_reflection.
