### ISSUE TITLE
Support for `SecurityCapabilities` tag in XML files

### ISSUE THREAD

**Issue by Hedreon** [rojo-rbx/rbx-dom#356]
Roblox recently implemented the `SecurityCapabilities` tag and because of this new implementation, Rojo can't build projects with the `SecurityCapabilities` tag in any roblox XML files.

**Comment by kennethloeffler** [comment]
rbx-dom is able to process files containing `SecurityCapabilities`. There's a warning because the type is unknown, and the decoded representation will not contain properties of this type, but it doesn't totally prevent usage. If `SecurityCapabilities` *does* grind everything to a halt right now (it doesn't in my testing), then there's a bug we need to fix.

I'll get started on this. Thanks for the report!
